// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.191018.6

#ifndef WINRT_Windows_Phone_Media_Devices_1_H
#define WINRT_Windows_Phone_Media_Devices_1_H
#include "winrt/impl/Windows.Phone.Media.Devices.0.h"
WINRT_EXPORT namespace winrt::Windows::Phone::Media::Devices
{
    struct __declspec(empty_bases) IAudioRoutingManager :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAudioRoutingManager>
    {
        IAudioRoutingManager(std::nullptr_t = nullptr) noexcept {}
        IAudioRoutingManager(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAudioRoutingManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAudioRoutingManagerStatics>
    {
        IAudioRoutingManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IAudioRoutingManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
