// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.191018.6

#ifndef WINRT_Windows_Phone_System_Profile_0_H
#define WINRT_Windows_Phone_System_Profile_0_H
WINRT_EXPORT namespace winrt::Windows::Phone::System::Profile
{
    struct IRetailModeStatics;
    struct RetailMode;
}
namespace winrt::impl
{
    template <> struct category<Windows::Phone::System::Profile::IRetailModeStatics>{ using type = interface_category; };
    template <> struct category<Windows::Phone::System::Profile::RetailMode>{ using type = class_category; };
    template <> inline constexpr auto& name_v<Windows::Phone::System::Profile::RetailMode>{ L"Windows.Phone.System.Profile.RetailMode" };
#ifndef WINRT_LEAN_AND_MEAN
    template <> inline constexpr auto& name_v<Windows::Phone::System::Profile::IRetailModeStatics>{ L"Windows.Phone.System.Profile.IRetailModeStatics" };
#endif
    template <> inline constexpr guid guid_v<Windows::Phone::System::Profile::IRetailModeStatics>{ 0xD7DED029,0xFDDA,0x43E7,{ 0x93,0xFB,0xE5,0x3A,0xB6,0xE8,0x9E,0xC3 } };
    template <> struct abi<Windows::Phone::System::Profile::IRetailModeStatics>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_RetailModeEnabled(bool*) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Windows_Phone_System_Profile_IRetailModeStatics
    {
        [[nodiscard]] auto RetailModeEnabled() const;
    };
    template <> struct consume<Windows::Phone::System::Profile::IRetailModeStatics>
    {
        template <typename D> using type = consume_Windows_Phone_System_Profile_IRetailModeStatics<D>;
    };
}
#endif
